### ISSUE TITLE
translate the shoutbox

### ISSUE THREAD

**Issue by Ency69** [NodeBB-Community/nodebb-plugin-shoutbox#105]
Hello,

I own a french forum and for the purpuses of it, I would like to translate the shoutbox plugin as much as I could, is there any quick way to do it ?

by as much as I could I would like at least to know how to change de "Send" text and the "enter message". If by chance I could translate more (as in the options) that would be real nice :)

Thank you !

**Comment by Schamper** [comment]
For your own (hacky) purpose, you could just edit the relevant files in your `node_modules` folder. Translation is something that needs to be added though, but will take slightly more effort.
