### ISSUE TITLE
Shoutbox widget doesn't render/loads on 1.5.3

### ISSUE THREAD

**Issue by fais3000** [NodeBB-Community/nodebb-plugin-shoutbox#111]
Cross referencing from https://community.nodebb.org/topic/11096/upgrade-from-1-5-2-to-1-5-3-breaks-shoubox-plugin

Experimented [here](http://chatrooms.talkwithstranger.com/free-online-chat-rooms) (Shoutbox on the right)

Works till this [commit](https://github.com/NodeBB/NodeBB/commit/956df9d7d7677e313b7f11c848be5e7b772327d7)
running with mongoDB

**Comment by barisusakli** [comment]
https://github.com/NodeBB-Community/nodebb-plugin-shoutbox/pull/123
