### ISSUE TITLE
Broken on NodeBB v1.7.2

### ISSUE THREAD

**Issue by PongoPygmaeus** [NodeBB-Community/nodebb-plugin-shoutbox#114]
> TypeError: e is not a function

```
n                            default.js:93:14
send/this.register/<     default.js:82:6
dispatch                      jquery.js:5205:15


add/m.handle             jquery.js:5014:5
```

**Comment by PongoPygmaeus** [comment]
![screenshot from 2017-12-24 20-30-04](https://user-images.githubusercontent.com/25397189/34332747-68260722-e8e9-11e7-9eb8-c0ff0aa902c1.png)

**Comment by FaizanZahid** [comment]
perhaps, as i see, its broken on nodebb v1.7.3

**Comment by Schamper** [comment]
Feel free to submit a PR to fix this.

**Comment by FaizanZahid** [comment]
I m happy to submit PR for all other things, however I m not very familiar
with this one. Can we ask help from node bb admin teams?

**Comment by barisusakli** [comment]
https://github.com/NodeBB-Community/nodebb-plugin-shoutbox/pull/123
