### ISSUE TITLE
Warning on widgets.render for rendering the shoutbox widget

### ISSUE THREAD

**Issue by thinkin** [NodeBB-Community/nodebb-plugin-shoutbox#115]
when i install shoutbox, i find errors as follow
`3/1 19:25:34 [329959] - [33mwarn[39m: [widgets.render] passing a string is deprecated!, filter:widget.render:shoutbox. Please set hookData.html in your plugin.`

**Comment by Schamper** [comment]
Looks more like a warning to me 👍 but thanks for the notification.

**Comment by barisusakli** [comment]
https://github.com/NodeBB-Community/nodebb-plugin-shoutbox/pull/123
