### ISSUE TITLE
Disable "Create Gist" and "View Archive" buttons

### ISSUE THREAD

**Issue by zoharm** [NodeBB-Community/nodebb-plugin-shoutbox#120]
As per the title, at the bottom of the shoutbox there are two buttons, I would like to be able to remove them.

(I am on NodeBB v1.10.1 and Shoutbox plugin v0.3.4)

Thank you!

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/132801709-221e6ef8-da0f-4ef8-9896-9988744c08b7.png)
