### ISSUE TITLE
Timestamps are broken

### ISSUE THREAD

**Issue by Schamper** [NodeBB-Community/nodebb-plugin-shoutbox#88]

**Comment by Holyphoenix** [comment]
I noticed what this issue is better now.  It looks like it displays the timestamps in backwards order.  The first shout has the latest shouts timestamp.  And the newest shout has the oldest displayed shouts timestamp.

**Comment by nagornyi** [comment]
Yes, exactly same issue for me - all timestamps are in backwards order.
